name: flutter_app_plant_fyp
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none"

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.10.0
  firebase_database: ^10.1.0
  intl: ^0.18.0

flutter:
  uses-material-design: true
